config/routes.rb
Rails.application.routes.draw do

  root 'computings#index'

  get 'computings/:id/count_first' => 'computings#count_first', as: :count_first
  get 'computings/:id/count_second' => 'computings#count_second', as: :count_second

  resources :computings do
    resources :setellites
  end
  

end

app/models/computing.rb
require 'matrix'

class Computing < ActiveRecord::Base
  has_many :setellites, dependent: :destroy

  def solve_first
  	stls = []
  	self.setellites.each do |s|
  	  stls.push(s) 
  	end
  	a_coord =[[stls[0].x, stls[0].y, stls[0].z],
             [stls[1].x, stls[1].y, stls[1].z],
             [stls[2].x, stls[2].y, stls[2].z],
             [stls[3].x, stls[3].y, stls[3].z]]
    p = [stls[0].R, stls[1].R, stls[2].R, stls[3].R]

	coords = [0, 0, 0, 0]
	errors = [100, 100, 100, 100]
	eps = 0.01
	c = 299792458

	while errors[0] > eps || errors[1] > eps || errors[2] > eps || errors[3] > eps
	  begin
	    x1 = Math.sqrt(p[0]**2 - (coords[1]-a_coord[0][1])**2 - (coords[2]-a_coord[0][2])**2 - (coords[3]*c)**2) - a_coord[0][0]
	    x2 = -(Math.sqrt(p[0]**2 - (coords[1]-a_coord[0][1])**2 - (coords[2]-a_coord[0][2])**2 - (coords[3]*c)**2) - a_coord[0][0])
	  rescue
	  	x1 = Math.sqrt((p[0]**2 - (coords[1]-a_coord[0][1])**2 - (coords[2]-a_coord[0][2])**2 - (coords[3]*c)**2).abs) - a_coord[0][0]
	    x2 = -(Math.sqrt((p[0]**2 - (coords[1]-a_coord[0][1])**2 - (coords[2]-a_coord[0][2])**2 - (coords[3]*c)**2).abs) - a_coord[0][0])
	  end

	  begin
	  	y1 = Math.sqrt(p[1]**2 - (coords[0]-a_coord[1][0])**2 - (coords[2]-a_coord[1][2])**2 - (coords[3]*c)**2) - a_coord[1][1]
	    y2 = -(Math.sqrt(p[1]**2 - (coords[0]-a_coord[1][0])**2 - (coords[2]-a_coord[1][2])**2 - (coords[3]*c)**2) - a_coord[1][1])
	  rescue
	  	y1 = Math.sqrt((p[1]**2 - (coords[0]-a_coord[1][0])**2 - (coords[2]-a_coord[1][2])**2 - (coords[3]*c)**2).abs) - a_coord[1][1]
	    y2 = -(Math.sqrt((p[1]**2 - (coords[0]-a_coord[1][0])**2 - (coords[2]-a_coord[1][2])**2 - (coords[3]*c)**2).abs) - a_coord[1][1])
	  end

	  begin
	  	z1 = Math.sqrt(p[2]**2 - (coords[1]-a_coord[2][1])**2 - (coords[0]-a_coord[2][1])**2 - (coords[3]*c)**2) - a_coord[2][2]
	    z2 = -(Math.sqrt(p[2]**2 - (coords[1]-a_coord[2][1])**2 - (coords[0]-a_coord[2][1])**2 - (coords[3]*c)**2) - a_coord[2][2])
	  rescue
	  	z1 = Math.sqrt((p[2]**2 - (coords[1]-a_coord[2][1])**2 - (coords[0]-a_coord[2][1])**2 - (coords[3]*c)**2).abs) - a_coord[2][2]
	    z2 = -(Math.sqrt((p[2]**2 - (coords[1]-a_coord[2][1])**2 - (coords[0]-a_coord[2][1])**2 - (coords[3]*c)**2).abs) - a_coord[2][2])
	  end

	  begin
	  	t1 = Math.sqrt((p[3]**2 - (coords[1]-a_coord[3][1])**2 - (coords[2]-a_coord[3][2])**2 - (coords[0]-a_coord[3][0])**2)/c**2)
	    t2 = -(Math.sqrt((p[3]**2 - (coords[1]-a_coord[3][1])**2 - (coords[2]-a_coord[3][2])**2 - (coords[0]-a_coord[3][0])**2)/c**2))
	  rescue
	  	t1 = Math.sqrt((p[3]**2 - (coords[1]-a_coord[3][1])**2 - (coords[2]-a_coord[3][2])**2 - (coords[0]-a_coord[3][0])**2).abs/c**2)
	    t2 = -(Math.sqrt((p[3]**2 - (coords[1]-a_coord[3][1])**2 - (coords[2]-a_coord[3][2])**2 - (coords[0]-a_coord[3][0])**2).abs/c**2))
	  end

	  if (x1-coords[0]).abs < (x2-coords[0]).abs
	  	errors[0] = x1 - coords[0]
	  	coords[0] = x1
	  else
	  	errors[0] = x2 - coords[0]
	  	coords[0] = x2
	  end

	  if (y1-coords[1]).abs < (y2-coords[1]).abs
	  	errors[1] = y1 - coords[1] 
	  	coords[1] = y1
	  else
	  	errors[1] = y2 - coords[1]
	  	coords[1] = y2
	  end

	  if (z1-coords[2]).abs < (z2-coords[2]).abs
	  	errors[2] = z1 - coords[2] 
	  	coords[2] = z1
	  else
	  	errors[2] = z2 - coords[2]
	  	coords[2] = z2
	  end

	  if (t1-coords[3]).abs < (t2-coords[3]).abs
	  	errors[3] = t1 - coords[3] 
	  	coords[3] = t1
	  else
	  	errors[3] = t2 - coords[3]
	  	coords[3] = t2
	  end
	end
	return coords
  end

  def solve_second
  	stls = []
  	self.setellites.each do |s|
  	  stls.push(s) 
  	end
  	a_coord = Matrix[[stls[0].x, stls[0].y, stls[0].z],
             [stls[1].x, stls[1].y, stls[1].z],
             [stls[2].x, stls[2].y, stls[2].z],
             [stls[3].x, stls[3].y, stls[3].z]]
    p = Matrix[[stls[0].R, stls[1].R, stls[2].R, stls[3].R]]

	x = 0
	y = 0
	z = 0
	t = 0

	epsl = 10
	dx = epsl * 10
	dy = epsl * 10
	dz = epsl * 10
	dt = epsl * 10

	apred = Matrix[[x, y, z, t]]
	da = Matrix[[dx, dy, dz, dt]]

	while da[0,0] > epsl || da[0,1] > epsl || da[0,2] > epsl || da[0,3] > epsl 
	  a = Matrix[[x, y, z, t]]
	  r = Matrix[]
	  pr = Matrix[]
	  d = Matrix[]
	  l = Matrix[]
	  0.upto(3) { r = Matrix.rows(r.to_a << [x, y, z, t]) }
	  input_pr = []
	  input_l = []
	  0.upto(3) do |i|
	  	input_pr.push(Math.sqrt((a_coord[i,0]-r[0,0])**2+(a_coord[i,1]-r[0,1])**2+(a_coord[i,2]-r[0,2])**2))
	  end
	  pr = Matrix.rows(pr.to_a << input_pr)
	  0.upto(3) do |i|
	  	input_d = []
	  	0.upto(2) do |j|
	  	  input_d.push((a_coord[i,j]-r[0,i])/pr[0,i])
	  	end
	  	d = Matrix.rows(d.to_a << input_d)
	  	input_l.push(pr[0,i]-p[0,i])
	  end
	  l = Matrix.rows(l.to_a << input_l)
	  w1 = Matrix.identity(4)

	  dr = (d.transpose*w1*d).inverse*d.transpose*w1*l.transpose
	  a1 = []
	  0.upto(2) do |i|
	  	a1.push(a[0,i] + dr[i,0])
	  end
	  a1[3] = a[0,3]
	  x, y, z = a1[0], a1[1], a1[2]
	  dx = (a1[0] - apred[0,0]).abs
	  dy = (a1[1] - apred[0,1]).abs
	  dz = (a1[2] - apred[0,2]).abs
	  dt = (a1[3] - apred[0,3]).abs
	  new_da = Matrix.rows([] << [dx, dy, dz, dt])
	  da = new_da
	  new_apred = Matrix.rows([] << a1)
	  apred = new_apred
	end
	return apred.to_a
  end
end

app/models/setellite.rb
class Setellite < ActiveRecord::Base
  belongs_to :computing
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/computings_controller.rb
class ComputingsController < ApplicationController
  before_action :get_computing, only: [:show, :edit, :update, :destroy, :count_first, :count_second]

  def count_first
    @answer = @computing.solve_first
  end

  def count_second
    @answer = @computing.solve_second
  end

  def index
  	@computings = Computing.all
  end

  def show
    @setellites = @computing.setellites
  end

  def new
    @computing = Computing.new
  end

  def edit
  end

  def create
    @computing = Computing.create(computing_params)
    redirect_to computings_path
  end

  def update
    @computing.update_attributes(computing_params)
    redirect_to @computing
  end

  def destroy
    @computing.destroy
  end

  private

  def computing_params
  	params.require(:computing).permit(:name)
  end

  def get_computing
    @computing = Computing.find(params[:id])
  end

end

app/controllers/setellites_controller.rb
class SetellitesController < ApplicationController

  before_action :get_setellite, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    get_computing
    @setellite = @computing.setellites.build
  end

  def edit
  end

  def create
    get_computing
    @setellite = @computing.setellites.create(setellite_params)
    redirect_to @computing
  end

  def update
    @setellite.update_attributes(setellite_params)
    redirect_to([@setellite.computing, @setellite])
  end

  def destroy
    @setellite.destroy
    redirect_to @computing
  end

  private

  def setellite_params
    params.require(:setellite).permit(:name, :x, :y, :z, :R)
  end

  def get_computing
    @computing = Computing.find(params[:computing_id])
  end

  def get_setellite
    get_computing
    @setellite = @computing.setellites.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/computings_helper.rb
module ComputingsHelper
end

app/helpers/setellites_helper.rb
module SetellitesHelper
end

app/views/computings/count_first.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-3"> </div>
    <div class="col-xs-6">
    <div class = "jumbotron">
      <h1><%= @computing.name %></h1>
      <h3>Answers with 1-st method</h3>
      <ul>
        <li>X: <%= @answer[0] %></li>
        <li>Y: <%= @answer[1] %></li>
        <li>Z: <%= @answer[2] %></li>
        <li>T: <%= @answer[3] %></li>
      </ul>
      <p></p>
      <%= link_to "Back", computing_path(@computing), class: "btn btn-default"%>
    </div>
  </div>
  <div class="col-xs-3"> </div>
  </div>
</div>

app/views/computings/count_second.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-3"> </div>
    <div class="col-xs-6">
    <div class = "jumbotron">
      <h1><%= @computing.name %></h1>
      <h3>Answers with 2-nd method</h3>
      <ul>
        <li>X: <%= @answer[0][0] %></li>
        <li>Y: <%= @answer[0][1] %></li>
        <li>Z: <%= @answer[0][2] %></li>
        <li>T: <%= @answer[0][3] %></li>
      </ul>
      <p></p>
      <%= link_to "Back", computing_path(@computing), class: "btn btn-default"%>
    </div>
  </div>
  <div class="col-xs-3"> </div>
  </div>
</div>

app/views/computings/index.html.erb
<div class="container-fluid">
  <div class="row">
  	<div class="col-xs-3"> </div>
  	<div class="col-xs-6">
	  <div class = "jumbotron">
	    <h1>Computings</h1>
	    <br>
        <% @computings.each do |computing| %>
          <h4><%= link_to computing.name, computing, class: 'link-info' %></h4>
        <% end %>
        <br>
        <%= link_to "New computing", new_computing_path, class: "btn btn-default"%>
      </div>
	</div>
	<div class="col-xs-3"> </div>
  </div>
</div>

app/views/computings/new.html.erb
<div class="container-fluid">
  <div class="row">
  	<div class="col-xs-3"> </div>
  	<div class="col-xs-6">
	  <div class = "jumbotron">
	    <%= bootstrap_form_for(@computing) do |f| %>
  		  <h4><%= f.text_field :name %></h4>
  		  <%= f.submit class: "btn btn-info" %>
	    <% end %>
	    <p></p>
	    <%= link_to "Back", computings_path, class: "btn btn-default"%>
	  </div>
	</div>
	<div class="col-xs-3"> </div>
  </div>
</div>

app/views/computings/show.html.erb
<div class="container-fluid">
  <div class="row">
  	<div class="col-xs-3"> </div>
  	<div class="col-xs-6">
	  <div class = "jumbotron">
	  	<h1><%= @computing.name %></h1>
	  	<% unless @setellites.empty? %>
	  	  <h3>Setellites</h3>
	  	  <% @setellites.each do |s| %>
	  	    <h4>Name: <%= link_to s.name, computing_setellite_path(@computing.id, s.id), class: "link-info" %></h4>
	  	    <ul>
	  	      <li>X: <%= s.x %></li>
	  	      <li>Y: <%= s.y %></li>
	  	      <li>Z: <%= s.z %></li>
	  	      <li>R: <%= s.R %></li>
	  	    </ul>
	  	  <% end %>
	  	<% end %>
	  	<%= link_to "Add setellite", new_computing_setellite_path(@computing), class: "btn btn-info" %>
	  	<%= link_to "Solve with the 1-st method", count_first_url(@computing), class: "btn btn-info" %>
	  	<%= link_to "Solve with the 2-d method", count_second_url(@computing), class: "btn btn-info" %>
	    <p></p>
	    <%= link_to "Back", computings_path, class: "btn btn-default"%>
	  </div>
	</div>
	<div class="col-xs-3"> </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Navi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/setellites/edit.html.erb
<div class="container-fluid">
  <div class="row">
  	<div class="col-xs-3"> </div>
  	<div class="col-xs-6">
	  <div class = "jumbotron">
	  	<h1>Creating new setellite</h1>
	  	<br>
	    <%= bootstrap_form_for([@setellite.computing, @setellite]) do |f| %>
  		  <h4><%= f.text_field :name %></h4>
  		  <h4><%= f.text_field :x %></h4>
  		  <h4><%= f.text_field :y %></h4>
  		  <h4><%= f.text_field :z %></h4>
  		  <h4><%= f.text_field :R %></h4>
  		  <%= f.submit class: "btn btn-info" %>
	    <% end %>
	    <p></p>
	    <%= link_to "Back", computing_setellite_path(@computing.id, @setellite.id), class: "btn btn-default"%>
	  </div>
	</div>
	<div class="col-xs-3"> </div>
  </div>
</div>

app/views/setellites/new.html.erb
<div class="container-fluid">
  <div class="row">
  	<div class="col-xs-3"> </div>
  	<div class="col-xs-6">
	  <div class = "jumbotron">
	  	<h1>Creating new setellite</h1>
	  	<br>
	    <%= bootstrap_form_for([@setellite.computing, @setellite]) do |f| %>
  		  <h4><%= f.text_field :name %></h4>
  		  <h4><%= f.text_field :x %></h4>
  		  <h4><%= f.text_field :y %></h4>
  		  <h4><%= f.text_field :z %></h4>
  		  <h4><%= f.text_field :R %></h4>
  		  <%= f.submit class: "btn btn-info" %>
	    <% end %>
	    <p></p>
	    <%= link_to "Back", computings_path, class: "btn btn-default"%>
	  </div>
	</div>
	<div class="col-xs-3"> </div>
  </div>
</div>

app/views/setellites/show.html.erb
<div class="container-fluid">
  <div class="row">
  	<div class="col-xs-3"> </div>
  	<div class="col-xs-6">
	  <div class = "jumbotron">
	  	<h1><%= @setellite.name %></h1>
	  	<br>
	  	<h4>X: <%= @setellite.x %></h4>
	  	<h4>Y: <%= @setellite.y %></h4>
	  	<h4>Z: <%= @setellite.z %></h4>
	  	<h4>R: <%= @setellite.R %></h4>
	  	<%= link_to "Edit setellite", edit_computing_setellite_path(@computing, @setellite), class: "btn btn-info" %>
	  	<%= link_to "Destroy setellite", computing_setellite_path(@computing, @setellite), method: :delete, data: {confirm: "Are you sure?"},class: "btn btn-danger" %>
	    <p></p>
	    <%= link_to "Back", @computing, class: "btn btn-default"%>
	  </div>
	</div>
	<div class="col-xs-3"> </div>
  </div>
</div>